name: screen_ocr
description: Screen Capture + Myanmar OCR
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tesseract_ocr: ^0.4.30
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - assets/tessdata_config.json
    - assets/tessdata/
